# To avoid having to repeat the command again and again 
[all:vars]
ansible_user=vagrant 
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_python_interpreter=/usr/bin/python3

[masters]
master1 ansible_host=192.168.56.10 
master2 ansible_host=192.168.56.11 
master3 ansible_host=192.168.56.12 

[workers]
agent1 ansible_host=192.168.56.13 

[loadbalancers]
lb-master ansible_host=192.168.56.9 
lb-backup ansible_host=192.168.56.15 

[all:children]
masters
loadbalancers
workers


; ansible all -m ping 