apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-earthdx-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: reactjs-earthdx-frontend
  template:
    metadata:
      labels:
        app: reactjs-earthdx-frontend
    spec:
      containers:
      - name: reactjs-earthdx-frontend
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-earthdx-service
spec:
  selector:
    app: reactjs-earthdx-frontend
  ports:
  - port: 80
    targetPort: 80
# kubectl apply -f deployment.yaml


# To access your service by accessing localhost:8080
# kubectl port-forward service/reactjs-earthdx-service 8080:80