# using common role 
---
- name: Install nginx with playbook 
  hosts: nfs-servers,nfs-clients
  become: true 
  gather_facts: true 
  roles: 
    - role: common 
  
# ansible-playbook -i inventory2.yaml playbooks/common-playbook.yml