# Services (HAProxy + Keepalived )
---
- name: Configure Load Balancers
  hosts: loadbalancers
  become: true
  roles:
    - role: haproxy
    - role: keepalived
  # post_tasks: tasks will run after role is completed 
  post_tasks:
    - name: Verify HAProxy is running
      service:
        name: haproxy
        state: started
        enabled: yes
    - name: Verify Keepalived is running 
      service: 
        name: keepalived 
        state: started 
        enabled: yes 

# ansible-playbook playbooks/loadbalancers-playbook.yaml